export const AuthExceptions = {
    ALREADY_REGISTERED: 'User with this credentials already exists!',
    INVALID_PHONE: 'Invalid phone',
    USER_NOT_VERIFY: 'User is not verify',
    USER_NOT_FOUND: 'User with this credentials not found!',
    USERS_NOT_FOUND: 'Users with this credentials not found!',
    PASSWORD_DOES_NOT_MATCH: `Passwords don't match`,
    WRONG_REFRESH_TOKEN: 'Wrong refresh token',
    WRONG_DATE_OF_BIRTH: 'Не верная дата рождения',
    CODE_IS_VALIDATE: 'Code is valid',
    CODE_EXPIRED: 'Code expired',
    TOKEN_NOT_FOUND: 'Resresh token not found!',
    TOKEN_FAULT: 'The token was not found or the token is not valid',
    CODE_NOT_CORRECT: 'Проверьте код из сообщения или запросите новый',
    ACCESS_DENIED: 'access denied',
    TIME_HAS_EXPIRED: 'The time for password recovery has expired',
    EMAIL_NOT_CONFIRM: 'You have not confirmed email',
    UNREGISTERED: 'Unregistered',
    USER_DO_NOT_HAVE_INFO: 'The user has no personal information',
    NOT_FOUND: 'Not found',
    SMS_WAIT: 'Please wait 1 minute before asking again',
    SMS_ERR: 'Sms error',
    SMS_SENT: 'Sms sent',
    VERIFICATION_NOT_FOUND: 'Verification not found! Try registration again',

};