export const AuthExceptions = {
    ALREADY_REGISTERED: 'User with this credentials already exists!',
    INVALID_PHONE: 'Invalid phone',
    TRY_AGAIN: 'Что-то пошло не так, попробуйте зарегистрироваться заново',
    USER_NOT_VERIFY: 'User is not verify',
    USER_CAN_NOT_CREATED: 'Пациент не фожет быть создан',
    USER_NOT_FOUND: 'User with this credentials not found!',
    USERS_NOT_FOUND: 'Users with this credentials not found!',
    PASSWORD_DOES_NOT_MATCH: `Passwords don't match`,
    WRONG_REFRESH_TOKEN: 'Wrong refresh token',
    WRONG_DATE_OF_BIRTH: 'Не верная дата рождения',
    CODE_IS_VALIDATE: 'Code is valid',
    CODE_EXPIRED: 'Code expired',
    TOKEN_NOT_FOUND: 'Resresh token not found!',
    TOKEN_FAULT: 'The token was not found or the token is not valid',
    CODE_NOT_CORRECT: 'Проверьте код из сообщения или запросите новый',
    ACCESS_DENIED: 'access denied',
    TIME_HAS_EXPIRED: 'The time for password recovery has expired',
    EMAIL_NOT_CONFIRM: 'You have not confirmed email',
    UNREGISTERED: 'Unregistered',
    USER_DO_NOT_HAVE_INFO: 'The user has no personal information',
    NOT_FOUND: 'Not found',
    SMS_SERVICE_UNAVAILABLE: 'Смс сервис недоступен, попробуйте позже',
    SMS_WAIT: 'Please wait 1 minute before asking again',
    SMS_ERR: 'Sms error',
    SMS_SENT: 'Sms sent',
    VERIFICATION_NOT_FOUND: 'Verification not found! Try registration again',
    PASSCODE_ALREADY_EXISTS:'Код пароль уже установлен',
    PASSCODE_INVALID:'Код пароль не верный',
    PASSCODE_NOT_FOUND:'Код пароль не найден',
    CHALLENGE_INVALID: 'Invalid or expired challenge',
    SIGNATURE_INVALID: 'Invalid signature',
    BIOMETRIC_NOT_FOUND: 'Biometric not found',
    WARD_CAN_NOT_BE_ADDED: 'Ward can not be added',
    WARD_CAN_NOT_BE_DELETED: 'Ward can not be deleted',

};